<!doctype html>
<html lang="en-gb" class="no-js">
<head>
<title><?php echo "$headerstr" ?></title>
<meta charset="utf-8">
<meta name="Description" content="<?php echo "$descstr" ?>" />
<!-- Favicon --> 
<link rel="shortcut icon" href="images/favicon.ico">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<link rel="stylesheet" href="css/reset.css" type="text/css" />
<link rel="stylesheet" href="css/style.css" type="text/css" />
<link rel="stylesheet" href="css/font-awesome.css" type="text/css" />      
<link rel="stylesheet" media="screen" href="css/responsive-layouts.css" type="text/css" />  

</head>

<body>
<div class="site_wrapper">
<div class="boxed_wrapper">
    <div class="container_full">
        <div class="one">
    		<div id="logo"><a href="/"><img src="images/logo-kbd-large.png" alt="Komuniti Bebas Denggi" border="0"></a></div><!-- end logo -->
			<div class="three_fourth span40">
			<ul id="menu"><li><a href="#">reduce</a></li>
			<li><a href="#">educate</a></li>
			<li><a href="#">activate</a></li>
			<li><a href="#">protect</a></li></ul>
			</div>
</div>
         </div><!-- end top section -->
<div class="one bg_lightgrey">
<div class="container">
<div class="one_fifth bg_darkred text_white col_height">your denggue alert</div>
<div class="bg_lightred col_height"><span class="text_big">100</span> <span class="text_white">cases in <a href="#" class="white">Subang Jaya</a></span>
<span class="one_last"><a href="#" class="white"><i class="fa fa-cog icon-white"></i>customize your alert</a></span></div>
</div> <!-- end container -->


